# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI tests /linting for SN-CAST

on:
  push:
    branches: [ "master", "oop-refactor" ]
  pull_request:
    branches: [ "master", "oop-refactor" ]

permissions:
  contents: read

jobs:
  build:
    name : Continuous Integration Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file : pyproject.toml
    
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        #Â pin uv version 
        version: '0.9.13'
    - name : Install project and dependencies
      run: |
        uv sync --locked  --dev
    
    - name: Lint with ruff
      run: |
        uv run ruff check .
        uv run ruff format --check .
    
    - name: Test with pytest
      run: |
        uv run pytest


